### ISSUE TITLE
how to Install this compiler?

### ISSUE THREAD

**Issue by Sanjaysinghg** [asherkin/spider#13]
Please tell how to install this compiler. Thank You.

**Comment by asherkin** [comment]
I'm afraid my answer hasn't changed since #4 - but the gist of it is run `grunt` to build the files as documented in the README, then you need to serve the `build` directory to your users.

**Comment by Sanjaysinghg** [comment]
I am sorry but i am new to this compiler so i dont know much about it. Why dont you give direct finalised files?

**Comment by Sanjaysinghg** [comment]
I am currently using webhost and want to add this compiler there.
