### ISSUE TITLE
FireFox 64.0 Not supported In Latets Release

### ISSUE THREAD

**Issue by marco-hiiamu** [asherkin/spider#19]
![Screen Shot 2019-05-20 at 1 52 39 PM](https://user-images.githubusercontent.com/33091989/58044696-0aa33880-7b06-11e9-907a-f581217e8bf3.png)
running FireFox version 64.0 on MacOS 10.13.6

**Comment by asherkin** [comment]
I'm afraid I don't provided support for self-hosted installs, only the version hosted at https://spider.limetech.io/.
