### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by AquaVadis** [asherkin/spider#3]
Hey bro i have problem installing the compiler it says: Your browser its not supported.

**Comment by asherkin** [comment]
Clearly, your browser is not supported.

Supported Browsers:
- Chrome - Version ~20+
- Firefox - Version 20+
- Internet Explorer - Version 10+

**Comment by AquaVadis** [comment]
But when i open the compiler from https://spider.limetech.org/ i dont have that
